### ISSUE TITLE
¿Algún error en el archivo que acabo de subir?

### ISSUE THREAD

**Issue by sergiocanto1** [mcgalindo/trabajo01grupotd2023#3]
Acabo de subir un archivo que contiene 2 problemas de incertidumbre resueltos. Comentar si hay algún fallo

**Comment by Julosa612** [comment]
Tienes que meter tus dos ejercicios resueltos en el fichero EnunciadosSolucionGrupo.Rmd y los dos enunciados sin soluciones en el fichero EnunciadosGrupo.Rmd no aparte
